// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoi4Mmcv0a_zcfHrQClwEKCm3FK5wzNWY',
    appId: '1:413898594267:web:xxxxxxxxxxxxxxxxxx',
    messagingSenderId: '413898594267',
    projectId: 'ezeyway-2f869',
    authDomain: 'ezeyway-2f869.firebaseapp.com',
    storageBucket: 'ezeyway-2f869.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoi4Mmcv0a_zcfHrQClwEKCm3FK5wzNWY',
    appId: '1:413898594267:android:a1836521ce3ca5252d79fe',
    messagingSenderId: '413898594267',
    projectId: 'ezeyway-2f869',
    storageBucket: 'ezeyway-2f869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoi4Mmcv0a_zcfHrQClwEKCm3FK5wzNWY',
    appId: '1:413898594267:ios:xxxxxxxxxxxxxxxxxx',
    messagingSenderId: '413898594267',
    projectId: 'ezeyway-2f869',
    storageBucket: 'ezeyway-2f869.firebasestorage.app',
    iosBundleId: 'com.ezeyway.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoi4Mmcv0a_zcfHrQClwEKCm3FK5wzNWY',
    appId: '1:413898594267:ios:xxxxxxxxxxxxxxxxxx',
    messagingSenderId: '413898594267',
    projectId: 'ezeyway-2f869',
    storageBucket: 'ezeyway-2f869.firebasestorage.app',
    iosBundleId: 'com.ezeyway.app',
  );
}